//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataManagement
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WithUDBEntities : DbContext
    {
        public WithUDBEntities()
            : base("name=WithUDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Activity> Activity { get; set; }
        public virtual DbSet<Activity_File> Activity_File { get; set; }
        public virtual DbSet<File> File { get; set; }
        public virtual DbSet<lst_Category> lst_Category { get; set; }
        public virtual DbSet<lst_City> lst_City { get; set; }
        public virtual DbSet<lst_Cost> lst_Cost { get; set; }
        public virtual DbSet<lst_State> lst_State { get; set; }
        public virtual DbSet<Table> Table { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
